### ISSUE TITLE
Formato Formulario de TRANSFERENCIA

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#21]
Según lo coordinado con la unidad de activos fijos, es necesario realizar los siguientes cambios en el reporte de TRANSFERENCIA:

Mostrar los datos de ubicación según el siguiente orden:
Ciudad: Cochabamba
Oficina: Oficina CTO Jordan
Dirección: Piso 1, Informática

Adicionar en la cabecera los datos del funcionario origen y funcionario destino de la transferencia
Adicionar la columna Denominación antes de la columna Descripción
Quitar la paginación de la cabecera porque ya esta en el pie de pagina
Quitar el estado de la cabecera, o colocarlo donde esta la paginación superior
Quitar las columnas Tipo Activo, MArca, Nro Serie,Fecha de Compra
Adicionar la columna Observaciones

Adicionar el nombre del * Custodio en el campo de firma
Adicionar una leyenda después de las firmas con letra pequeña que indique lo siguiente:
* Esta casilla será firmada por personal que trabaja en la empresa pero que no figura en las planillas de BoA.

[abc.pdf](https://github.com/boabo/sis_kactivos_fijos/files/1395494/abc.pdf)

**Comment by rchumacero** [comment]
Se hace la adecuación del formulario
