### ISSUE TITLE
Incidente al registrar modificacion de la dirección de un activo fijo

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#22]
Al registrar una modificación de dirección en produccion para un activo fijo desde la interfaz Principal, pestaña Modificaciones, sale el incidente: 51187540

Revisando el log el mensaje indica: record #*#v_parametros#*# has no field #*#monto_compra_orig_ant#*#

**Comment by rchumacero** [comment]
Resuelto
