### ISSUE TITLE
Formulario ALTA de Activos Fijos

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#25]
Según lo coordinado con la unidad de activos fijos, es necesario realizar los siguientes cambios en el reporte de ALTA de ACTIVOS:

Mostrar los datos de ubicación según el siguiente orden:
Ciudad: Cochabamba
Oficina: Oficina CTO Jordan
Dirección: Piso 1, Informática

Adicionar la columna Denominación antes de la columna Descripción
Quitar la paginación de la cabecera porque ya esta en el pie de pagina
Quitar el estado de la cabecera, o colocarlo donde esta la paginación superior
Quitar las columnas Tipo Activo, MArca, Nro Serie
Adicionar la columna Observaciones
Adicionar la columna Fecha de Inicio Depreciación
Adicionar las columna Monto 87% y Monto 100%
Adicionar la columna Nro C31
Mostrar el Grupo en el que clasifico el activo en reemplazo del Codigo toda vez que aun no tiene codigo asignado.

[alta de activosbc.pdf](https://github.com/boabo/sis_kactivos_fijos/files/1398987/alta.de.activosbc.pdf)

**Comment by rchumacero** [comment]
Se hace la adecuación del formulario
