### ISSUE TITLE
No filtra por codigo de activo Fijo

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#29]
Cuando se registra un proceso de devolución de activo fijo Sin Detalle, al intentar añadir manualmente los activos al proceso mediante el botón nuevo, si se coloca el código en el combo de activos, se queda cargando y al final no lista nada.

Se probó con el numero de proceso KAF-DEVOLU-000007-2017 y el código de activo  04.04.01.0060

Si no se pone nada en el combo y solo se lista sus valores, tarda en mostrar pero al final es posible seleccionar alguno de ellos y registrarlo manualmente.

**Comment by rchumacero** [comment]
Se hizo un registro de prueba  de movimiento de Devolución (KAF-DEVOL-000009-2017)  y el filtro funciona correctamente
