### ISSUE TITLE
Habilitar el reporte de activos fijos por responsable para inventario según el formato del ERP 1

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#30]
Habilitar el reporte de activos fijos por responsable para inventario según el formato del ERP 1 adjunto

[For-inventarioActivos.pdf](https://github.com/boabo/sis_kactivos_fijos/files/1432674/For-inventarioActivos.pdf)

**Comment by rchumacero** [comment]
Reporte creado
