### ISSUE TITLE
Imprimir varias etiquetas segun un rango de codigos

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#35]
Hay casos donde se dan de alta muchos activos de una sola vez, en esos casos es útil mandar a imprimir todas las etiquetas que estén dentro de un rango de números de activos.

La anterior versión cuenta co la funcionalidad de generar por activos o por clasificacion

**Comment by rchumacero** [comment]
El sistema cuenta con el reporte solicitado.

![reporte_codigos_qr](https://user-images.githubusercontent.com/2071354/32410451-c8d19da4-c196-11e7-9c06-fc7fc73ce7dc.png)
