### ISSUE TITLE
Listado de funcionarios repetidos, adicionar filtro por departamento de activos y corregir fecha

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#38]
En el Reporte de Activos fijos por responsable - Inventario, el listado de funcionarios está mostrando todos los cargos por los que pasó un funcionario y no el cargo vigente ocasionando que los nombres se repitan como se muestra a continuacion.

![image](https://user-images.githubusercontent.com/18399403/32609299-a0f0ded8-c535-11e7-9bc7-254088fb1c28.png)

Es necesario también adicionar en el formulario el campo Departamento de Activos, toda vez que el inventario de activos se realiza por separado, es decir Equipos de computación por un lado y el resto de los activos por otro.

![image](https://user-images.githubusercontent.com/18399403/32609546-6a76729a-c536-11e7-971b-2445202e38f6.png)

El campo Fecha Asignación, está mostrando fechas que no corresponden a las reales.

**Comment by rchumacero** [comment]
Se agrega el combo para seleccion del departamento.
Se corrige el combo de funcionarios enviando la fecha actual para el despliegue del cargo actual.
El tema de las fechas, requiere analisis

**Comment by grovervelasquez** [comment]
En este mismo reporte se hay algunos datos de Lugar de Asignación que no son los mismos que los que se tiene en la versión anterior de activos fijos.

Por ejemplo para la funcionaria Cinthia Teresa Mercado Perasso y sus activos del departamento de informática en todas las oficinas en el ERP 1 sale lo siguiente: Oficina Aeropuerto TJA

![image](https://user-images.githubusercontent.com/18399403/32662143-de112910-c5ff-11e7-910a-d0dad39e2050.png)

Ese mismo activo en el Reporte del ERP 2 figura en Oficina Aeropuerto CBB

![image](https://user-images.githubusercontent.com/18399403/32662240-37c63ad6-c600-11e7-88d8-39c33e17415c.png)

Revisando el último movimiento de asignación de ese activo en el ERP 2, la fecha de asignación no coincide, y entrando al detalle del movimiento en la columna Lugar sale Undefined.

![image](https://user-images.githubusercontent.com/18399403/32663751-6901f090-c605-11e7-81f5-bd981e3bf9f9.png)

![image](https://user-images.githubusercontent.com/18399403/32663825-b260f4f2-c605-11e7-8787-5d1cec2ba2e2.png)

Es como si la informacion migrada no fuese la misma o como si faltara migrar la ultima asignacion con las fechas y oficina correctas.

**Comment by rchumacero** [comment]
Corregido
