### ISSUE TITLE
Link para editar activos fijos en blanco

### ISSUE THREAD

**Issue by grovervelasquez** [boabo/sis_kactivos_fijos#42]
Al presionar en el link para ver el activos fijo, no muestra nada en el listado

![image](https://user-images.githubusercontent.com/18399403/33098505-01dd8c0c-cee4-11e7-929d-e239930404c7.png)

![image](https://user-images.githubusercontent.com/18399403/33098467-ed0f487e-cee3-11e7-92fd-f52775793e37.png)

**Comment by rchumacero** [comment]
Solucionado. El problema era un inner join con la tabla catalogo
